name: 'Doxygen'

on:
  push:
    branches: [ main ]
    paths: [ 'docs/**', 'examples/**', 'src/adiar/*.h' ]
  pull_request:
    branches: [ main ]
    paths: [ 'docs/**', 'examples/**', 'src/adiar/*.h' ]

jobs:
  run_doxygen:
    name: 'Compile Doxygen'
    runs-on: ubuntu-latest

    steps:
    # Git repo set up
    - name: Checkout commit
      uses: actions/checkout@v5
      with:
        submodules: 'recursive'

    - name: Install C++ project dependencies
      run: sudo apt install libboost-all-dev

    - name: Install Doxygen and Graphviz
      run: sudo apt install doxygen graphviz

    # CMake build and create docs
    - name: CMake build
      working-directory: ${{github.workspace}}
      run: |
        cmake -E make_directory ${{github.workspace}}/build
        cd ${{github.workspace}}/build
        cmake ..

    - name: Make adiar_docs
      working-directory: ${{github.workspace}}/build
      run: make adiar_docs

    # Deploy on GitHub Pages if pushed to main
    - uses: JamesIves/github-pages-deploy-action@v4.7.4
      if: ${{ github.event_name == 'push' }}
      with:
        branch: gh-pages
        folder: ${{github.workspace}}/build/docs/html/
