name: examples

on:
  push:
    branches: [ main ]
    paths: [ 'examples/**', 'src/adiar/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'examples/**', 'src/adiar/**' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  run-minor:
    name: 'Example: ${{ matrix.name }}'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'Basic'
            target: adiar_example-basic
          - name: 'Builder'
            target: adiar_example-builder
          - name: 'Functional'
            target: adiar_example-functional

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: 'recursive'

    - name: Apt | install boost
      run: |
        sudo apt update
        sudo apt install libboost-all-dev

    - name: CMake | build
      run: |
        cmake -E make_directory ${{runner.workspace}}/build
        cd ${{runner.workspace}}/build
        cmake $GITHUB_WORKSPACE -D CMAKE_BUILD_TYPE=Release && cmake --build . --target ${{ matrix.target }}

    - name: Run | ...
      working-directory: ${{runner.workspace}}/build
      run: ./examples/${{ matrix.target }} -M 1024

  run-queens:
    name: 'Example: Queens'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - N: '1 2 3 4 5 6 7 8 9 10 11 12 13 14'

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: 'recursive'

    - name: Apt | install boost
      run: |
        sudo apt update
        sudo apt install libboost-all-dev

    - name: CMake | build
      run: |
        cmake -E make_directory ${{runner.workspace}}/build
        cd ${{runner.workspace}}/build
        cmake $GITHUB_WORKSPACE -D CMAKE_BUILD_TYPE=Release && cmake --build . --target adiar_example-queens

    - name: Run | queens
      working-directory: ${{runner.workspace}}/build
      run: for n in ${{ matrix.N }}; do ./examples/adiar_example-queens -N $n -M 1024; done
