name: static analysis

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  include-guards:
    name: inclusion guards
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Check src/adiar/adiar.h
      uses: sbeyer/include-guards-check-action@v2.0.0
      with:
        path: src/adiar
        pattern: '{file}'
        only: 'adiar\.h'

    - name: Check other files in src/adiar/* files
      uses: sbeyer/include-guards-check-action@v2.0.0
      with:
        path: src
        pattern: '{dirs}_{file}'
        ignore: 'adiar/adiar\.h'


  cppcheck:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: 'recursive'

      - name: cppcheck
        uses: JacobDomagala/StaticAnalysis@v0.0.8
        with:
          # Project Settings
          language: c++
          use_cmake: true
          cmake_args: "-D ADIAR_STATS=ON"

          # Dependencies
          apt_pckgs: libboost-all-dev
          exclude_dir: external

          # Analysis Settings
          # clang_tidy_args: <???>
          cppcheck_args: --enable=all --suppress=missingIncludeSystem
