name: test

on:
  push:
    branches: [ master ]
    paths: 'src/adiar/**'
  pull_request:
    branches: [ master ]
    paths: 'src/adiar/**'

jobs:

  test:
    name: 'Unit test (incl. code coverage)'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Apt | install boost aptitude graphviz lcov
      run: sudo apt install libboost-all-dev aptitude graphviz lcov

    - name: CMake | mkdir build
      run: cmake -E make_directory ${{runner.workspace}}/build
    - name: CMake | configure
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -D CMAKE_BUILD_TYPE=Debug -D CODE_COVERAGE=ON
    - name: CMake | build unit tests
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --target test_unit

    - name: Run unit tests
      working-directory: ${{runner.workspace}}/build
      run: ./test/test_unit --reporter=info --colorizer=light

    - name: Generate code coverage report
      working-directory: ${{runner.workspace}}
      run: |
        lcov -c -d build/src/adiar/ -o ./coverage.info
        lcov --remove coverage.info --output-file coverage.info "/usr/*" "*/external/*" "./test/*"

    - name: Upload report to Codecov.io
      working-directory: ${{runner.workspace}}
      run: bash <(curl -s https://codecov.io/bash) -f coverage.info -t ${{ secrets.CODECOV_TOKEN }} || echo "Codecov did not collect coverage reports"
